name: dart_kubernetes_client
version: 0.0.1
author: Dmitrii Bocharov <bdshadow@gmail.com>
environment:
  sdk: '>=2.1.0 <3.0.0'
dependencies:
  http: ^0.12.0+2
  json_serializable: ^3.2.3
  test: ^1.9.4